baseurl = "https://massimo-nocentini.github.io"
DefaultContentLanguage = "en"
title = "Massimo Nocentini"
# Using theme as git submodule
theme = "beautifulhugo"
# Or when using theme as hugo module
# theme = "github.com/halogenica/beautifulhugo"
pygmentsStyle = "monokai"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"

[security]
  allowContent = ['^text/html$', '^text/markdown$']

[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2

[Params]
  homeTitle = "A small measure of peace" # Set a different text for the header on the home page
  subtitle = "This site is a collection of Massimo Nocentini's papers, notes, memos and source code."
  mainSections = ["post","posts"]
#  logo = "samurai.jpg" # Expecting square dimensions
  favicon = "samurai.jpg"
  dateFormat = "January 2, 2006"
  toc = true
  commit = true
  rss = true
  comments = false
  readingTime = true
  wordCount = true
#  useHLJS = true
  socialShare = false
  delayDisqus = false
  showRelatedPosts = true
#  cusdisID = "XXX" # Get your App id from cusdis.com
  hideAuthor = false
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"
#  disclaimerText = "The opinions expressed herein are my own personal opinions and do not represent my employer’s view in any way."

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Params.author]
  # Set only your "username" for default hosts and full URLs otherwise (e.g., "https://MyGitLab.org/username")
  name = "Massimo Nocentini"
  website = "https://massimo-nocentini.github.io"
  email = "massimo.nocentini@gmail.com"
  #facebook = "username"
  github = "massimo-nocentini"
  gitlab = "massimo-nocentini"
  #bitbucket = "username"
  #twitter = "username"
  #reddit = "username"
  #linkedin = "username"
  #xing = "username"
  #stackoverflow = "users/XXXXXXX/username"
  #snapchat = "username"
  #instagram = "username"
  #youtube = "user/username" # or channel/channelname
  #soundcloud = "username"
  #spotify = "username"
  #bandcamp = "username"
  #itchio = "username"
  #vk = "username"
  paypal = "username"
  telegram = "username"
  #500px = "username"
  #codepen = "username"
  #mastodon = "url"
  #kaggle = "username"
  #weibo = "username"
  #slack = "username"
  #medium = "username"
  discord = "invite code (https://discord.gg/massimo.nocentini)"
  #strava = "userid"
  #lastfm = "username"
  #bluesky = "username"

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 1

#[[menu.main]]
#    name = "Blog"
#    url = ""
#    weight = 2

#[[menu.main]]
#    name = "Pages"
#    url = "page/"
#    weight = 2

#[[menu.main]]
#    name = "Tags"
#    url = "tags"
#    weight = 3

#[[menu.main]]
#    name = "Categories"
#    url = "categories/"
#    weight = 4

[[menu.main]]
    identifier = "externals"
    name = "Externals"
    weight = 5

[[menu.main]]
    parent = "externals"
    name = "Data Structures in Smalltalk"
    url = "https://massimo-nocentini.github.io/Booklet-DSst/"
    weight = 1

[[menu.main]]
    parent = "externals"
    name = "Crate libpq-rs"
    url = "https://massimo-nocentini.github.io/libpq-rs/libpq/index.html"
    weight = 2

[[menu.main]]
    parent = "externals"
    name = "Crate igraph-rs"
    url = "https://massimo-nocentini.github.io/igraph-rs/igraph/"
    weight = 3