services:

  wolfram-engine:
    image: massimonocentini/wolframengine:wstpkernel
    restart: always
    environment:
      - WOLFRAM_PORT=8080
    ports:
      - 8081:8080
    volumes:
      - ~/.WolframEngine/Licensing:/home/wolframengine/.WolframEngine/Licensing

  chicken-scheme-basic:
    image: massimonocentini/chicken-scheme:5.4.0-myeggs
    command: |
      /bin/bash -c "
                  cd aux.scm/src && make test -B && cp test/*.html /home/testsuites && cd ../../ &&
                  cd fds.scm/src && make test -B && cp test/*.html /home/testsuites && cd ../../ &&
                  echo 'Done'
                 "
    volumes:
      - ./testsuites:/home/testsuites

  chicken-scheme-wolfram-base:
    image: massimonocentini/chicken-scheme:5.4.0-myeggs
    depends_on:
      - wolfram-engine
    environment:
      - CHICKEN_WOLFRAM_HOST=wolfram-engine
      - CHICKEN_WOLFRAM_PORT=8080
    command: |
      /bin/bash -c "sleep 10s && cd wolfram.scm/src/test && csi -s test.scm && cp *.html /home/testsuites && echo 'Done'"
    volumes:
      - ./testsuites:/home/testsuites

  chicken-scheme-wolfram-hansei-base:
    image: massimonocentini/chicken-scheme:5.4.0-myeggs
    depends_on:
      - wolfram-engine
    environment:
      - CHICKEN_WOLFRAM_HOST=wolfram-engine
      - CHICKEN_WOLFRAM_PORT=8080
    command: |
      /bin/bash -c "sleep 10s && cd wolfram.scm/src/test && csi -s hansei-base.scm && cp *.html /home/testsuites && echo 'Done'"
    volumes:
      - ./testsuites:/home/testsuites

  chicken-scheme-wolfram-hansei-ve:
    image: massimonocentini/chicken-scheme:5.4.0-myeggs
    depends_on:
      - wolfram-engine
    environment:
      - CHICKEN_WOLFRAM_HOST=wolfram-engine
      - CHICKEN_WOLFRAM_PORT=8080
    command: |
      /bin/bash -c "sleep 10s && cd wolfram.scm/src/test && csi -s hansei-variable-elimination.scm && cp *.html /home/testsuites && echo 'Done'"
    volumes:
      - ./testsuites:/home/testsuites

  chicken-scheme-githubio:
    image: massimonocentini/chicken-scheme:5.4.0-myeggs
    command: |
      /bin/bash -c "cd mn-githubio/ && make index"
    volumes:
      - ./:/home/mn-githubio/
