
localhost:
	jupyter-notebook --port=5900 --ip=150.217.37.50


presentation-make:
	jupyter-nbconvert presentation-first-year.ipynb \
        --to slides \
        --stdout \
        --reveal-prefix http://cdn.bootcss.com/reveal.js/3.1.0 > talk.html

serve-fatberry.disia.unifi.it:
	PYTHONPATH=../../../programming-contests/competitive-programming/python-libs/ jupyter-notebook --no-browser --port=5900 --ip=150.217.37.116

